---
title: "Carpentries Example Streamflow Analysis"
author: Jess Wilhelm
output: github_document
---
This is an example script developed during a Carpentries workshop. Within it, we will develop a workflow to:

1.) Prepare an R environment
2.) Download and save USGS streamflow data
3.) Tidy, QAQC, and gap-fill the data
4.) Report some summary statistics

## 1. Prepare the R environment

we will load any relevant packages and set the default for our code visibility in the final report. 

building our first code chunk!!

```{r setup}
knitr::opts_chunk$set(echo = TRUE)
library(dataRetrieval) 
library(dplyr)
library(zoo)
library(lubridate)
library(ggplot2)
```

if we knit a file it runs all of the code. 

## 2. Download and save USGS streamflow data

We will use the 'readNWISdv' function from the 'dataRetrieval package to download stream stage data for the USGS gage on the Arkansas River near Larned. 
{r download-data}

```
# gage id
usgs_id <- "07141220"

# download the data
  data_raw <-
    readNWISdv(siteNumber = usgs_id,
    parameterCd = "00065",
    startDate = "2018-10-01",
    endDate = "2021-09-30")

# inspect the data
summary(data_raw)

# save the data
write.csv(data_raw, "data/ExampleStreamStage_Raw.csv")
```
## 3. Tidy, gap-fill, and QAQC data

In this section, we will perform some basic data cleaning operations to get out data ready for further analysis.
{r clean-data}

```
# create a new data frame with better column names
data_tidy <-
  data_raw %>%
  rename(stage_ft = X_00065_00003,
         stageQAcode = X_00065_00003_cd) %>%
  select(-agency_cd, -site_no)

#look at the new data frame
head(data_tidy)

#first step in communing with data is to plot
ggplot(data_tidy, aes(x = Date, y = stage_ft)) +
  geom_line()
  
  # check for missing dates by comparing all possible dates to the dates you have
  first_date <- min(data_tidy$Date)
  last_date <- max(data_tidy$Date)
  all_dates <- seq(first_date, last_date, by = "day") # make vector of all dates
  length(all_dates) == length(data_tidy$Date)
```
# determine missing dates
missing_dates <- all_dates[!(all_dates %in% data_tidy$Date)]

# add missing dates to data frame
new_dates <- data.frame(Date = missing_dates,
                          stage_ft = NA,
                          stage_QAcode = "Gapfill")
                          
  data_clean <- 
  bind_rows(data_tidy, new_dates) %>%
  arrange(Date)
  
  summary(data_clean)
  
  #fill in those gaps using linear interpolation
  data_clean$stage_ft <- na.approx(data_clean$stage_ft)
  
  summary(data_clean)
  
  # plot and inspect
  ggplot(data_clean, aes(x = Date, y = stage_ft, color = stage_QAcode)) +
  geom_point()
  
  #save data
  write.csv(data_clean, "data/ExampleStreamStage_Clean.csv")
  
  ```
  
  ### 4. write up some summary statistics.
  
We analyzed data from USGS `r usgs_id`. During the period of record, the 
maximum stage was `r max(data_clean$stage_ft)` and the minimum stage was `r min(data_clean$stage_ft)`. There were a total of `r sum(data_clean$stage_QAcode == "Gapfill")' missing dates that we gap-filled using linear interpolation.
  
  




